#ifndef RESPONSE_STATUS_H
#define RESPONSE_STATUS_H

#define RESPONSE_STATUS_SIZE 0x4U

typedef enum {
    BUG = 0,
    SUCCESS = 1,
    QUEUE_CREATED = 91,
    COMMAND_RECEIVED = 92,
    QUEUE_IS_EMPTY = 93,
    RESULT_LOGGED = 94,
    RESULT_NOT_LOGGED = 450,
    BAD_REQUEST = 360,
    ZERO_USERS = 890,
    SUCCESS_PUSH = 180,
    SUCCESS_EXIT = 181,
    ACCESS_LEVEL = 182,
    ADMIN_ADDED = 183,
    NO_PERMS_TO_PUSH = 540,
    NO_PERMS_TO_ADD_ADMINS = 541,
    NO_PERMS_TO_ADD_ADMINS_WITH_THIS_ACCESS_LEVEL = 542,
    NO_PERMS_TO_STOP = 543,
    INCORRECT_CHARACTERS = 544,
    LOGIN_IS_TOO_LONG = 545,
    LOGIN_IS_TOO_SHORT = 546,
    PASSWORD_IS_TOO_LONG = 547,
    PASSWORD_IS_TOO_SHORT = 548,
    INCORRECT_MARKING_OF_AUTH_DATA = 549,
} response_status;

#endif